name: ethel
channels:
  - conda-forge
  - defaults
dependencies:
  - black=22.10.0
  - isort=5.10.1
  - mypy=0.982
  - numpy=1.23.4
  - pre-commit=2.20.0
  - pydocstyle=6.1.1
  - pylint=2.15.5
  - pyside6=6.4.0
  - pytest=7.2.0
  - python=3.10.6
